package entities;
// Generated 29-11-2013 11:17:13 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Hug generated by hbm2java
 */
public class Hug  implements java.io.Serializable {


     private int id;
     private Student studentByStudent2;
     private Student studentByStudent1;
     private Date expiration;
     private Boolean mutual;

    public Hug() {
    }

	
    public Hug(int id, Student studentByStudent2, Student studentByStudent1) {
        this.id = id;
        this.studentByStudent2 = studentByStudent2;
        this.studentByStudent1 = studentByStudent1;
    }
    public Hug(int id, Student studentByStudent2, Student studentByStudent1, Date expiration, Boolean mutual) {
       this.id = id;
       this.studentByStudent2 = studentByStudent2;
       this.studentByStudent1 = studentByStudent1;
       this.expiration = expiration;
       this.mutual = mutual;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Student getStudentByStudent2() {
        return this.studentByStudent2;
    }
    
    public void setStudentByStudent2(Student studentByStudent2) {
        this.studentByStudent2 = studentByStudent2;
    }
    public Student getStudentByStudent1() {
        return this.studentByStudent1;
    }
    
    public void setStudentByStudent1(Student studentByStudent1) {
        this.studentByStudent1 = studentByStudent1;
    }
    public Date getExpiration() {
        return this.expiration;
    }
    
    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }
    public Boolean getMutual() {
        return this.mutual;
    }
    
    public void setMutual(Boolean mutual) {
        this.mutual = mutual;
    }




}


