package entities;
// Generated 03-10-2013 19:21:56 by Hibernate Tools 3.2.1.GA



/**
 * Relationship generated by hbm2java
 */
public class Relationship  implements java.io.Serializable {


     private int id;
     private Student studentByStudent2;
     private Student studentByStudent1;
     private String type;

    public Relationship() {
    }

	
    public Relationship(int id, Student studentByStudent2, Student studentByStudent1) {
        this.id = id;
        this.studentByStudent2 = studentByStudent2;
        this.studentByStudent1 = studentByStudent1;
    }
    public Relationship(int id, Student studentByStudent2, Student studentByStudent1, String type) {
       this.id = id;
       this.studentByStudent2 = studentByStudent2;
       this.studentByStudent1 = studentByStudent1;
       this.type = type;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Student getStudentByStudent2() {
        return this.studentByStudent2;
    }
    
    public void setStudentByStudent2(Student studentByStudent2) {
        this.studentByStudent2 = studentByStudent2;
    }
    public Student getStudentByStudent1() {
        return this.studentByStudent1;
    }
    
    public void setStudentByStudent1(Student studentByStudent1) {
        this.studentByStudent1 = studentByStudent1;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


