package entities;
// Generated 29-11-2013 11:07:25 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int id;
     private String name;
     private String surname;
     private String handle;
     private String address;
     private String password;
     private String salt;
     private Boolean isadmin;
     private Boolean issuspended;
     private Set interests = new HashSet(0);
     private Set hugsForStudent2 = new HashSet(0);
     private Set hugsForStudent1 = new HashSet(0);
     private Set relationshipsForStudent2 = new HashSet(0);
     private Set relationshipsForStudent1 = new HashSet(0);

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String name, String surname, String handle, String address, String password, String salt, Boolean isadmin, Boolean issuspended, Set interests, Set hugsForStudent2, Set hugsForStudent1, Set relationshipsForStudent2, Set relationshipsForStudent1) {
       this.id = id;
       this.name = name;
       this.surname = surname;
       this.handle = handle;
       this.address = address;
       this.password = password;
       this.salt = salt;
       this.isadmin = isadmin;
       this.issuspended = issuspended;
       this.interests = interests;
       this.hugsForStudent2 = hugsForStudent2;
       this.hugsForStudent1 = hugsForStudent1;
       this.relationshipsForStudent2 = relationshipsForStudent2;
       this.relationshipsForStudent1 = relationshipsForStudent1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getHandle() {
        return this.handle;
    }
    
    public void setHandle(String handle) {
        this.handle = handle;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Boolean getIsadmin() {
        return this.isadmin;
    }
    
    public void setIsadmin(Boolean isadmin) {
        this.isadmin = isadmin;
    }
    public Boolean getIssuspended() {
        return this.issuspended;
    }
    
    public void setIssuspended(Boolean issuspended) {
        this.issuspended = issuspended;
    }
    public Set getInterests() {
        return this.interests;
    }
    
    public void setInterests(Set interests) {
        this.interests = interests;
    }
    public Set getHugsForStudent2() {
        return this.hugsForStudent2;
    }
    
    public void setHugsForStudent2(Set hugsForStudent2) {
        this.hugsForStudent2 = hugsForStudent2;
    }
    public Set getHugsForStudent1() {
        return this.hugsForStudent1;
    }
    
    public void setHugsForStudent1(Set hugsForStudent1) {
        this.hugsForStudent1 = hugsForStudent1;
    }
    public Set getRelationshipsForStudent2() {
        return this.relationshipsForStudent2;
    }
    
    public void setRelationshipsForStudent2(Set relationshipsForStudent2) {
        this.relationshipsForStudent2 = relationshipsForStudent2;
    }
    public Set getRelationshipsForStudent1() {
        return this.relationshipsForStudent1;
    }
    
    public void setRelationshipsForStudent1(Set relationshipsForStudent1) {
        this.relationshipsForStudent1 = relationshipsForStudent1;
    }




}


