package dk.itu.ssase.hb.beans.model;
// Generated 29-11-2013 11:07:25 by Hibernate Tools 3.2.1.GA



/**
 * AlienRelation generated by hbm2java
 */
public class AlienRelation  implements java.io.Serializable {


     private int id;
     private AlienUser alienUserByAlien1;
     private AlienUser alienUserByAlien2;

    public AlienRelation() {
    }

	
    public AlienRelation(int id) {
        this.id = id;
    }
    public AlienRelation(int id, AlienUser alienUserByAlien1, AlienUser alienUserByAlien2) {
       this.id = id;
       this.alienUserByAlien1 = alienUserByAlien1;
       this.alienUserByAlien2 = alienUserByAlien2;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public AlienUser getAlienUserByAlien1() {
        return this.alienUserByAlien1;
    }
    
    public void setAlienUserByAlien1(AlienUser alienUserByAlien1) {
        this.alienUserByAlien1 = alienUserByAlien1;
    }
    public AlienUser getAlienUserByAlien2() {
        return this.alienUserByAlien2;
    }
    
    public void setAlienUserByAlien2(AlienUser alienUserByAlien2) {
        this.alienUserByAlien2 = alienUserByAlien2;
    }




}


