package dk.itu.ssase.hb.beans.model;
// Generated 29-11-2013 10:58:52 by Hibernate Tools 3.2.1.GA



/**
 * AlienRelation generated by hbm2java
 */
public class AlienRelation  implements java.io.Serializable {


     private int id;
     private Integer alien1;
     private Integer alien2;

    public AlienRelation() {
    }

	
    public AlienRelation(int id) {
        this.id = id;
    }
    public AlienRelation(int id, Integer alien1, Integer alien2) {
       this.id = id;
       this.alien1 = alien1;
       this.alien2 = alien2;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getAlien1() {
        return this.alien1;
    }
    
    public void setAlien1(Integer alien1) {
        this.alien1 = alien1;
    }
    public Integer getAlien2() {
        return this.alien2;
    }
    
    public void setAlien2(Integer alien2) {
        this.alien2 = alien2;
    }




}


