package dk.itu.ssase.hb.beans.model;
// Generated 29-11-2013 10:58:52 by Hibernate Tools 3.2.1.GA



/**
 * AlienUser generated by hbm2java
 */
public class AlienUser  implements java.io.Serializable {


     private int id;
     private String name;
     private String country;
     private String hobbies;
     private String profile;

    public AlienUser() {
    }

	
    public AlienUser(int id) {
        this.id = id;
    }
    public AlienUser(int id, String name, String country, String hobbies, String profile) {
       this.id = id;
       this.name = name;
       this.country = country;
       this.hobbies = hobbies;
       this.profile = profile;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getHobbies() {
        return this.hobbies;
    }
    
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }




}


