package dk.itu.ssase.hb.beans.model;
// Generated 27-10-2013 17:14:26 by Hibernate Tools 3.2.1.GA



/**
 * Relationship generated by hbm2java
 */
public class Relationship  implements java.io.Serializable {


     private int id;
     private Student student2;
     private Student student1;
     private RelaType type;
     private Boolean approved;

    public Relationship() {
    }

	
    public Relationship(int id, Student studentByStudent2, Student studentByStudent1, RelaType type) {
        this.id = id;
        this.student2 = studentByStudent2;
        this.student1 = studentByStudent1;
        this.type = type;
    }
    public Relationship(int id, Student studentByStudent2, Student studentByStudent1, RelaType type, Boolean approved) {
       this.id = id;
       this.student2 = studentByStudent2;
       this.student1 = studentByStudent1;
       this.type = type;
       this.approved = approved;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Student getStudent2() {
        return this.student2;
    }
    
    public void setStudent2(Student student2) {
        this.student2 = student2;
    }
    public Student getStudent1() {
        return this.student1;
    }
    
    public void setStudent1(Student student1) {
        this.student1 = student1;
    }
    public RelaType getType() {
        return this.type;
    }
    
    public void setType(RelaType type) {
        this.type = type;
    }
    public Boolean getApproved() {
        return this.approved;
    }
    
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }




}


