CREATE DATABASE ssase13
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       LC_COLLATE='C'
       LC_CTYPE='C'
       TEMPLATE=template0
       CONNECTION LIMIT = -1;
GRANT CONNECT, TEMPORARY ON DATABASE ssase13 TO public;
GRANT ALL ON DATABASE ssase13 TO postgres;
GRANT CONNECT ON DATABASE ssase13 TO tomcat;

